# Generated by Django 4.1.1 on 2022-09-17 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0004_alter_transacao_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='autor',
            field=models.CharField(max_length=100)
        ),
    ]
