# Generated by Django 4.1.1 on 2022-09-17 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0006_alter_transacao_valor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transacao',
            old_name='descricao',
            new_name='livro',
        ),
    ]
