# Generated by Django 4.1.1 on 2022-09-17 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0007_rename_descricao_transacao_livro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='valor',
        ),
        migrations.AddField(
            model_name='transacao',
            name='pag',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
            preserve_default=False,
        ),
    ]
