# Generated by Django 4.1.1 on 2022-09-17 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0008_remove_transacao_valor_transacao_pag'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='editora',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
