# Generated by Django 4.1.1 on 2022-09-17 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0009_transacao_editora'),
    ]

    operations = [
        migrations.AddField(
            model_name='transacao',
            name='ano',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=4),
            preserve_default=False,
        ),
    ]
