# Generated by Django 4.1.1 on 2022-09-17 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0011_alter_transacao_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transacao',
            name='data',
            field=models.DateTimeField(),
        ),
    ]
