# Generated by Django 4.1.1 on 2022-09-17 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contas', '0012_alter_transacao_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacao',
            name='data',
        ),
    ]
